/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo2_21552011235;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static uts_pbo2_21552011235.FDaftar21552011235.checkEmailIsReady;
import static uts_pbo2_21552011235.FDaftar21552011235.checkValidateEmaill;

/**
 *
 * @author albin
 */
public class FAlat2155201123511 extends javax.swing.JFrame {
    Connection conn = CKoneksi21552011235.getKoneksi();
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String sql, idUser, level, id, kosong;
    
    public FAlat2155201123511() {
        initComponents();
//        idUserOtomatis();
        tampilDataDivisi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
//    private void idUserOtomatis(){
//            try {
//                    st = conn.createStatement();
//                    sql = "SELECT * FROM tbluser order by idUser DESC";
//                    rs = st.executeQuery(sql);
//                      if (rs.next()) {
//                           idUser = rs.getString("idUser").substring(4);
//                           id = "" + (Integer.parseInt(idUser) + 1);
//                           kosong = "";
//                      if (id.length() == 1){
//                           kosong = "00";    
//                      } else if (id.length() == 2){
//                           kosong = "0";
//                      } else {
//                          kosong = "";
//                      }
//                      txtFieldTunjangan.setText("USER" + kosong + id);
//                      } else {
//                   txtFieldTunjangan.setText("USER001");
//                  }
//                  rs.close();
//                  st.close();
//            } catch (NumberFormatException | SQLException e) {
//        }
//}
// public static boolean checkEmailIsReady(String email) {
//        try {
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts_pbo2_21552011235", "root", "");
//            String query = "SELECT * FROM tbluser WHERE email=?";
//            PreparedStatement stmt = conn.prepareStatement(query);
//            stmt.setString(1, email);
//            ResultSet rs = stmt.executeQuery();
//            if (rs.next()) {
//                return true;
//            }
//            
//            // Tutup koneksi dan statement
//            rs.close();
//            stmt.close();
//            conn.close();
//        } catch (SQLException e) {
//            System.out.println("Error: " + e.getMessage());
//        }
//        return false;
//  }
  
// public static boolean checkValidateEmaill(String email) {
//        String regex = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";// Regular Expresion Email
//        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
//        Matcher matcher = pattern.matcher(email);
//        return matcher.matches();
//  }
  
// public boolean checkValidatePassword(String password) {
//    String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";  // Regular Expresion Password
//    Pattern pattern = Pattern.compile(passwordRegex);
//    Matcher matcher = pattern.matcher(password);
//    return matcher.matches();
//}
// 
  private void tampilDataDivisi (){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Divisi");
        model.addColumn("Nama Divisi");
        model.addColumn("Gaji Pokok");
        model.addColumn("Tunjangan");
         try {
             sql = "SELECT * FROM tbldivisi ORDER BY idDivisi ASC";
             st = conn.createStatement();
             rs = st.executeQuery(sql);
             while (rs.next()){
                 Object[] row = new Object[4];
                 row[0] = rs.getString("idDivisi");
                 row[1] = rs.getString("namaDivisi");
                 row[2] = rs.getString("gapok");
                 row[3] = rs.getString("tunjangan");
                 model.addRow(row);
             }
         tableAlat.setModel(model);
         }catch (Exception e){
             System.out.print(e);
             e.printStackTrace();
         }
    }
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldCari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnUbah = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFieldKodeAlat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldBiayaProduksi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlat = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFieldNamaAlat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldHargaJual1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Form Alat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        txtFieldCari.setBorder(null);
        txtFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCariActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 190, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("_____________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, 30));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png"))); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 40));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png"))); // NOI18N
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahMouseExited(evt);
            }
        });
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("_______________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 30));

        txtFieldKodeAlat.setBorder(null);
        txtFieldKodeAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldKodeAlatActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldKodeAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, 40));

        jLabel13.setText("Kode Alat");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("_______________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 30));

        txtFieldBiayaProduksi.setBorder(null);
        txtFieldBiayaProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldBiayaProduksiActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldBiayaProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 40));

        jLabel15.setText("Biaya Produksi");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tableAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 470, 150));

        jLabel9.setText("Masukan Kata Kunci");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("_______________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 30));

        txtFieldNamaAlat.setBorder(null);
        txtFieldNamaAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaAlatActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldNamaAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, 40));

        jLabel17.setText("Nama Alat");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataAlat.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("_______________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 260, 30));

        txtFieldHargaJual1.setBorder(null);
        txtFieldHargaJual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHargaJual1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldHargaJual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 190, 40));

        jLabel18.setText("Harga Jual");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCariActionPerformed

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal-hover.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseEntered
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnUbah.png")));
    }//GEN-LAST:event_btnUbahMouseEntered

    private void btnUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseExited
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnUbah-hover.png")));
    }//GEN-LAST:event_btnUbahMouseExited

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        txtFieldKodeAlat.setText(null);
        txtFieldBiayaProduksi.setText(null);
        txtFieldCari.setText(null);
    }//GEN-LAST:event_btnBatalMouseClicked

    private void txtFieldKodeAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldKodeAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKodeAlatActionPerformed

    private void txtFieldBiayaProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldBiayaProduksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldBiayaProduksiActionPerformed

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        int i = tableAlat.getSelectedRow();
        int ok = JOptionPane.showConfirmDialog (null," Apakah Anda Yakin Ingin "
        + "Mengedit Data ?","Konfirmasi Edit Data Divisi", JOptionPane.YES_NO_OPTION);
        
        String gapok = txtFieldBiayaProduksi.getText();
        String tunjangan = txtFieldCari.getText();
        
        if (ok==0){
            String idDivisi = tableAlat.getValueAt(i, 0).toString();
            java.sql.Connection connect = CKoneksi21552011235.getKoneksi();
            sql = "UPDATE `tbldivisi` SET `gapok` = '"+gapok+"',`tunjangan` = '"+tunjangan+"'"
                + "WHERE `tbldivisi`.`idDivisi` = '"+idDivisi+"';";
            
            try {
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(sql);
                ps.execute(sql);
                JOptionPane.showMessageDialog(null , "Data Berhasil Di Edit");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Di Edit!!!"+e);
            }finally{
                tampilDataDivisi();
            }
        }
    }//GEN-LAST:event_btnUbahMouseClicked

    private void tableAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlatMouseClicked
       int baris = tableAlat.getSelectedRow();
            txtFieldNamaAlat.setText(tableAlat.getValueAt(baris, 0).toString());
            txtFieldKodeAlat.setText(tableAlat.getValueAt(baris, 1).toString());
            txtFieldBiayaProduksi.setText(tableAlat.getValueAt(baris, 2).toString());
            txtFieldCari.setText(tableAlat.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tableAlatMouseClicked

    private void txtFieldNamaAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaAlatActionPerformed

    private void txtFieldHargaJual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHargaJual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaJual1ActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png")));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png")));
    }//GEN-LAST:event_btnBackMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAlat2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAlat2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAlat2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAlat2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAlat2155201123511().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAlat;
    private javax.swing.JTextField txtFieldBiayaProduksi;
    private javax.swing.JTextField txtFieldCari;
    private javax.swing.JTextField txtFieldHargaJual1;
    private javax.swing.JTextField txtFieldKodeAlat;
    private javax.swing.JTextField txtFieldNamaAlat;
    // End of variables declaration//GEN-END:variables
}
