/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo2_21552011235;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author albin
 */
public class FMenuUtama21552011235 extends javax.swing.JFrame {
    String level;
    String nama;
    
    public FMenuUtama21552011235() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnAdmin = new javax.swing.JMenu();
        btnProduksi = new javax.swing.JMenu();
        btnMarketing = new javax.swing.JMenu();
        btnUbahPassword = new javax.swing.JMenu();
        btnProfil = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenu();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-user-24.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
        });
        jMenuBar1.add(btnAdmin);

        btnProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-product-24.png"))); // NOI18N
        btnProduksi.setText("Produksi");
        btnProduksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProduksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProduksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProduksiMouseExited(evt);
            }
        });
        jMenuBar1.add(btnProduksi);

        btnMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-stocks-growth-24.png"))); // NOI18N
        btnMarketing.setText("Marketing");
        btnMarketing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMarketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMarketingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMarketingMouseExited(evt);
            }
        });
        jMenuBar1.add(btnMarketing);

        btnUbahPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-password-24.png"))); // NOI18N
        btnUbahPassword.setText("Ubah Password");
        btnUbahPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUbahPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUbahPasswordMouseExited(evt);
            }
        });
        jMenuBar1.add(btnUbahPassword);

        btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-test-account-24.png"))); // NOI18N
        btnProfil.setText("Profil");
        btnProfil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfilMouseExited(evt);
            }
        });
        jMenuBar1.add(btnProfil);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-logout-rounded-24.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        jMenuBar1.add(btnLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
       btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-user-24-hover.png")));
    }//GEN-LAST:event_btnAdminMouseEntered

    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
       btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-user-24.png")));
    }//GEN-LAST:event_btnAdminMouseExited

    private void btnProduksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduksiMouseEntered
       btnProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-product-24-hover.png")));
    }//GEN-LAST:event_btnProduksiMouseEntered

    private void btnProduksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduksiMouseExited
       btnProduksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-product-24.png")));
    }//GEN-LAST:event_btnProduksiMouseExited

    private void btnMarketingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarketingMouseEntered
       btnMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-stocks-growth-24-hover.png")));
    }//GEN-LAST:event_btnMarketingMouseEntered

    private void btnMarketingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarketingMouseExited
       btnMarketing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-stocks-growth-24.png")));
    }//GEN-LAST:event_btnMarketingMouseExited

    private void btnUbahPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseEntered
       btnUbahPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-password-24-hover.png")));
    }//GEN-LAST:event_btnUbahPasswordMouseEntered

    private void btnUbahPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahPasswordMouseExited
       btnUbahPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-password-24.png")));
    }//GEN-LAST:event_btnUbahPasswordMouseExited

    private void btnProfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfilMouseEntered
       btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-test-account-24-hover.png")));
    }//GEN-LAST:event_btnProfilMouseEntered

    private void btnProfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfilMouseExited
       btnProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-test-account-24.png")));
    }//GEN-LAST:event_btnProfilMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
       btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-logout-rounded-24-hover.png")));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
       btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-logout-rounded-24.png")));
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenuUtama21552011235().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAdmin;
    private javax.swing.JMenu btnLogout;
    private javax.swing.JMenu btnMarketing;
    private javax.swing.JMenu btnProduksi;
    private javax.swing.JMenu btnProfil;
    private javax.swing.JMenu btnUbahPassword;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
