/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo2_21552011235;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static uts_pbo2_21552011235.FDaftar21552011235.checkEmailIsReady;
import static uts_pbo2_21552011235.FDaftar21552011235.checkValidateEmaill;

/**
 *
 * @author albin
 */
public class FPenjualan2155201123511 extends javax.swing.JFrame {
    Connection conn = CKoneksi21552011235.getKoneksi();
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String sql, idUser, level, id, kosong;
    
    public FPenjualan2155201123511() {
        initComponents();
        idUserOtomatis();
        tampilDataPenjualan ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    private void idUserOtomatis(){
            try {
                    st = conn.createStatement();
                    sql = "SELECT * FROM tbluser order by idUser DESC";
                    rs = st.executeQuery(sql);
                      if (rs.next()) {
                           idUser = rs.getString("idUser").substring(4);
                           id = "" + (Integer.parseInt(idUser) + 1);
                           kosong = "";
                      if (id.length() == 1){
                           kosong = "00";    
                      } else if (id.length() == 2){
                           kosong = "0";
                      } else {
                          kosong = "";
                      }
                      txtFieldKodePenjualan.setText("USER" + kosong + id);
                      } else {
                   txtFieldKodePenjualan.setText("USER001");
                  }
                  rs.close();
                  st.close();
            } catch (NumberFormatException | SQLException e) {
        }
}
 public static boolean checkEmailIsReady(String email) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_uts_pbo2_21552011235", "root", "");
            String query = "SELECT * FROM tbluser WHERE email=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, email);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                return true;
            }
            
            // Tutup koneksi dan statement
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return false;
  }
  
 public static boolean checkValidateEmaill(String email) {
        String regex = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";// Regular Expresion Email
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
  }
  
 public boolean checkValidatePassword(String password) {
    String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";  // Regular Expresion Password
    Pattern pattern = Pattern.compile(passwordRegex);
    Matcher matcher = pattern.matcher(password);
    return matcher.matches();
}
 
  private void tampilDataPenjualan (){
        try {
            if (txtFieldKodePenjualan.getText().isEmpty()) {
                sql = "select * from tblpenjualan";
            }else{
                sql = "SELECT * FROM tblpenjualan WHERE "
                + "`kodeJual` LIKE '%"+txtFieldCari.getText()+"%' OR"
                + "`kodeAlat`  LIKE '%"+txtFieldCari.getText()+"%' OR "
                + "`kodePegawai`  LIKE '%"+txtFieldCari.getText()+"%' OR "
                + "`tglJual`  LIKE '%"+txtFieldCari.getText()+"%' OR "
                + "`jumlah` LIKE '%"+txtFieldCari.getText()+"%'";
            }
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
               model.addColumn(metaData.getColumnName(i));
            }
            while (rs.next()) {
               Object[] row = new Object[columnCount];
               for (int i = 1; i <= columnCount; i++) {
                  row[i - 1] = rs.getObject(i);
               }
               model.addRow(row);
            }
            tablePenjualan.setModel(model);
        } catch (Exception e) {
        }
    }
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldKodePenjualan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldHargaJual = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldNamaPegawai = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtFieldCari = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnTambahDataPenjualan = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comboBoxNamaAlat = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        dateTglPenjualan = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtFieldJumlah = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Form Penjualan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 30));

        txtFieldKodePenjualan.setBorder(null);
        txtFieldKodePenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldKodePenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldKodePenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("_______________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 30));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png"))); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, 50));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png"))); // NOI18N
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("_______________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 30));

        jLabel13.setText("Tanggal Penjualan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("_______________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 340, 30));

        txtFieldHargaJual.setBorder(null);
        txtFieldHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHargaJualActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 250, 40));

        jLabel15.setText("Harga Jual");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenjualan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 740, 240));

        jLabel9.setText("Kode Penjualan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("______________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 280, 30));

        txtFieldNamaPegawai.setBorder(null);
        txtFieldNamaPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaPegawaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldNamaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 230, 40));

        jLabel18.setText("Nama Pegawai");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("________________________________________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 260, 30));

        txtFieldCari.setBorder(null);
        txtFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCariActionPerformed(evt);
            }
        });
        txtFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 230, 30));

        jLabel20.setText("Masukan Kata Kunci");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 10));

        btnTambahDataPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataPenjualan.png"))); // NOI18N
        jPanel1.add(btnTambahDataPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 230, 50));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("_______________________________");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 210, 30));

        comboBoxNamaAlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxNamaAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        jLabel23.setText("Nama Alat");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 10));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));
        jPanel1.add(dateTglPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("______________________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 270, 30));

        txtFieldJumlah.setBorder(null);
        txtFieldJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 250, 40));

        jLabel17.setText("Jumlah");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldKodePenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldKodePenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKodePenjualanActionPerformed

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnKembaliDaftar.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnKembaliDaftar-hover.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnDaftar.png")));
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnDaftar-hover.png")));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        Flogin21552011235 fL = new Flogin21552011235();
        fL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void txtFieldHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaJualActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        if (txtFieldJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Pastikan data jumlah telah terisi. Ulangi kembali!", "DATA BELUM TERISI !", JOptionPane.WARNING_MESSAGE);
        } else {
            int ok = JOptionPane.showConfirmDialog (null," Apakah Anda Yakin Ingin "
            + "Mengedit Data ?","Konfirmasi Edit Data Divisi", JOptionPane.YES_NO_OPTION);


            if (ok==0){
                try {
                sql = "UPDATE tblPenjualan SET jumlah=? WHERE kodeJual=?";
                ps = conn.prepareStatement(sql);
                ps.setString(1, txtFieldJumlah.getText());
                
                ps.executeUpdate();
                tampilDataPenjualan();
                JOptionPane.showMessageDialog(null , "Data Berhasil Di Edit");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Data Gagal Di Edit!!!"+e);
                }
            }
        
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tablePenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenjualanMouseClicked
             
    }//GEN-LAST:event_tablePenjualanMouseClicked

    private void txtFieldNamaPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaPegawaiActionPerformed

    private void txtFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCariActionPerformed

    private void txtFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCariKeyReleased

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
       btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png")));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
       btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void txtFieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldJumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPenjualan2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPenjualan2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPenjualan2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPenjualan2155201123511.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPenjualan2155201123511().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel btnTambahDataPenjualan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxNamaAlat;
    private com.toedter.calendar.JDateChooser dateTglPenjualan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePenjualan;
    private javax.swing.JTextField txtFieldCari;
    private javax.swing.JTextField txtFieldHargaJual;
    private javax.swing.JTextField txtFieldJumlah;
    private javax.swing.JTextField txtFieldKodePenjualan;
    private javax.swing.JTextField txtFieldNamaPegawai;
    // End of variables declaration//GEN-END:variables
}
