/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuanDua;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author albin
 */
public class FDaftarerror extends javax.swing.JFrame {
    Connection conn = CKoneksi.getKoneksi();
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String sql, kodeUser, kode, kosong;
    
    
    private void kodeUserOtomatis() throws SQLException{
            try {
                    st = conn.createStatement();
                    sql = "SELECT * FROM tb_user order by kode_user DESC";
                    rs = st.executeQuery(sql);
                      if (rs.next()) {
                           kodeUser = rs.getString("kode_user").substring(1);
                           kode = "" + (Integer.parseInt(kodeUser) + 1);
                           kosong = "";
                      if (kode.length() == 1){
                           kosong = "00";    
                      } else if (kode.length() == 2){
                           kosong = "0";
                      } else {
                          kosong = "";
                      }
                      txtKodeUser.setText("U" + kosong + kode);
                      } else {
                   txtKodeUser.setText("U001");
                  }
                  rs.close();
                  st.close();
            } catch (NumberFormatException | SQLException e) {
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsernameEmail = new javax.swing.JTextField();
        txtKodeUser = new javax.swing.JTextField();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        btnDaftar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setResizable(false);

        jLabel1.setText("Semua Data Harus Di Isi !!!");

        jLabel2.setText("Kode User");

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        jLabel5.setText("Confirm Password");

        txtUsernameEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameEmailActionPerformed(evt);
            }
        });

        txtKodeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeUserActionPerformed(evt);
            }
        });

        txtPasswordConfirm.setText("jPasswordField1");

        btnDaftar.setText("Daftar");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        txtPassword.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsernameEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsernameEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btnDaftar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameEmailActionPerformed

    private void txtKodeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeUserActionPerformed

  public static boolean checkEmailExist(String email) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_toko", "root", "");
            String query = "SELECT * FROM tb_user WHERE username=?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, email);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                return true;
            }
            
            // Tutup koneksi dan statement
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return false;
  }
  
  public static boolean isValidEmail(String email) {
        String regex = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
       }
       
    // fungsi untuk mengecek apakah input password kuat
public boolean isStrongPassword(String password) {
    // regex untuk setiap karakter pada password
    String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
    Pattern pattern = Pattern.compile(passwordRegex);
    Matcher matcher = pattern.matcher(password);
    return matcher.matches();
}

//    if(rs.next()){
//    String userType = rs.getString("usertype");
//    if(userType.equals("admin")){
//        // your admin code here
//    }else{
//        // your user code here
//    }
//}
    
//                     try {
//                          String query = "SELECT * FROM tb_user WHERE username = ?";
//                          ps = conn.prepareStatement(query);
//                          ps.setString(2, txtUsernameEmail.getText());
//                          ps.executeQuery();
//                                if (rs.next()) {
//                                    JOptionPane.showMessageDialog(null, "Mohon maaf email telah terdaftar");
//                                  } 
//                    } catch (Exception e) {
//                        System.err.println("Exception: " + e.getMessage());
//                    }
   

    
    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
 if (txtUsernameEmail.getText().isEmpty() || txtPassword.getText().isEmpty() || txtPasswordConfirm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data harus diisi semua!");
        } else if (!txtPasswordConfirm.getText().equals(txtPassword.getText())) {
            JOptionPane.showMessageDialog(null, "Confirm Password harus sama dengan password!");
        }else{
            try {
             // cek email sudah ada atau belum
            if (checkEmailExist(txtUsernameEmail.getText())) { // email belum ada
               JOptionPane.showMessageDialog(null, "Email telah terdaftar, lakukan registrasi kembali!");

            } 
            else { // email ada dan cek format nya apakah sudah benar 
                  if (isValidEmail(txtUsernameEmail.getText())) {// format email benar
                  System.out.println("Email belum terdaftar");
                  System.out.println("format email benar");
                
                     //cek password lebih dari 8 itu kuat
                     String password = txtPassword.getText().toString();
                      if (isStrongPassword(password)) { // password kuat
                      JOptionPane.showMessageDialog(null, "Password Aman");
                      sql = "INSERT INTO tb_user VALUES (?, ?, ?, ?)";
                      ps = conn.prepareStatement(sql);
                      ps.setString(1, txtKodeUser.getText());
                      ps.setString(2, txtUsernameEmail.getText());
                      ps.setString(3, txtPassword.getText());
                      ps.setString(4, "Operator");
                      ps.executeUpdate();
                      JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                      FLogin fl = new FLogin();
                      this.dispose();
                      fl.setVisible(true);
                      ps.close();
                      } else { 
                          JOptionPane.showMessageDialog(null, "Password lemah, password harus menggunakan huruf besar ,angka dan simbol");
                      }                                
        } else {
            JOptionPane.showMessageDialog(null, "Format email salah, harap dengan benar");
        }
        }
                
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDaftarerror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDaftarerror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDaftarerror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDaftarerror.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDaftarerror().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtKodeUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JTextField txtUsernameEmail;
    // End of variables declaration//GEN-END:variables
}
