/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import koneksi.CKoneksi21552011235;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author albin
 */
public class FAlat21552011235 extends javax.swing.JFrame {
    Connection conn = CKoneksi21552011235.getKoneksi();
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String sql, kodeAlat, namaAlat, level, kode, a;
    boolean simpan = true;
    
    public FAlat21552011235() {
        initComponents();
        tampilDataAlat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
   private void kodeAlatOtomatis() {
    namaAlat = txtFieldNamaAlat.getText();
    String[] kata = namaAlat.split(" ");
    kode = "";
    if (kata.length == 1) {
        kode = kata[0].substring(0, 3).toUpperCase();
    } else {
        for (int i = 0; i < kata.length; i++) {
            kode += kata[i].substring(0, 1).toUpperCase();
        }
    }
    try {
        st = conn.createStatement();
        sql = "SELECT COUNT(*) AS jumlah FROM tblalat";
        rs = st.executeQuery(sql);
        if (rs.next()) {
            int jumlah = rs.getInt("jumlah");
            a = String.format("%03d", jumlah + 1);
            kode += a;
            txtFieldKodeAlat.setText(kode);
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
  
  private void tampilDataAlat (){
        try {
            if (txtFieldCari.getText().isEmpty()) {
                sql = "select * from tblalat";
            }else {
                sql = "SELECT * FROM tblalat WHERE "
                + "`kodeAlat` LIKE '%"+txtFieldCari.getText()+"%' OR"
                + "`namaAlat`  LIKE '%"+txtFieldCari.getText()+"%' OR "
                + "`biayaProduksi` LIKE '%"+txtFieldCari.getText()+"%' OR"
                + "`hargaJual` LIKE '%"+txtFieldCari.getText()+"%'";
            }
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
               model.addColumn(metaData.getColumnName(i));
            }
            while (rs.next()) {
               Object[] row = new Object[columnCount];
               for (int i = 1; i <= columnCount; i++) {
                  row[i - 1] = rs.getObject(i);
               }
               model.addRow(row);
            }
            tableAlat.setModel(model);
        } catch (Exception e) {
        }
    }
  
  private void btnSimpanDataAlat(){
        String kodeAlat = txtFieldKodeAlat.getText().trim();
        String namaAlat = txtFieldNamaAlat.getText().trim();
        String biayaProduksi = txtFieldBiayaProduksi.getText().trim();
        String hargaJual = txtFieldHargaJual.getText().trim();
        
        if (kodeAlat.isEmpty() || namaAlat.isEmpty() || biayaProduksi.isEmpty() || hargaJual.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Pastikan Data telah terisi semuanya. Ulangi kembali!", "DATA BELUM TERISI !", JOptionPane.WARNING_MESSAGE);
        }
        
        try {
            int biayaPrdksi = Integer.parseInt(biayaProduksi);
            int harga = Integer.parseInt(hargaJual);
            if (harga <= biayaPrdksi) {
            JOptionPane.showMessageDialog(this, "Harga jual harus lebih besar dari biaya produksi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
            String sql;
            PreparedStatement ps;
            if (simpan = true) {
                sql = "insert into tblalat values (?,?,?,?)";
                ps = conn.prepareStatement(sql);
                ps.setString(1, kodeAlat);
                ps.setString(2, namaAlat);
                ps.setString(3, biayaProduksi);
                ps.setString(4, hargaJual);
            }else{
                sql = "UPDATE tblalat SET biayaProduksi=?, hargaJual=?, WHERE namaAlat=?";
                ps = conn.prepareStatement(sql);
                ps.setString(1, biayaProduksi);
                ps.setString(2, hargaJual);
                ps.setString(3, namaAlat);
            }
            
            ps.executeUpdate();
            
            String pesan;
            if (simpan) {
                pesan = "Data berhasil disimpan";
            } else {
                pesan = "Data berhasil diubah";
            }
            tampilDataAlat();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Biaya produksi dan harga jual harus diisi hanya angka!", "ISI DATA SALAH !", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi sebuah kesalahan saat menyimpan data alat", "ISI DATA ERROR !", JOptionPane.ERROR_MESSAGE);
        }
  }
  
  private void btnBatal(){
        txtFieldKodeAlat.setText(null);
        txtFieldNamaAlat.setText(null);
        txtFieldBiayaProduksi.setText(null);
        txtFieldHargaJual.setText(null);
  }
 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldCari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFieldKodeAlat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldBiayaProduksi = new javax.swing.JTextField();
        titleBiayaProduksi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlat = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFieldNamaAlat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnTambahDataAlat = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldHargaJual = new javax.swing.JTextField();
        titleHargaJual = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Form Alat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        txtFieldCari.setBorder(null);
        txtFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCariActionPerformed(evt);
            }
        });
        txtFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 180, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("_____________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 210, 30));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png"))); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 40));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png"))); // NOI18N
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 130, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("_______________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 230, 30));

        txtFieldKodeAlat.setBorder(null);
        txtFieldKodeAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldKodeAlatActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldKodeAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, 40));

        jLabel13.setText("Kode Alat");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("_______________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 30));

        txtFieldBiayaProduksi.setBorder(null);
        txtFieldBiayaProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldBiayaProduksiActionPerformed(evt);
            }
        });
        txtFieldBiayaProduksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldBiayaProduksiKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldBiayaProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 40));

        titleBiayaProduksi.setText("Biaya Produksi");
        jPanel1.add(titleBiayaProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        tableAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 470, 150));

        jLabel9.setText("Masukan Kata Kunci");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("_______________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 30));

        txtFieldNamaAlat.setBorder(null);
        txtFieldNamaAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaAlatActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldNamaAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, 40));

        jLabel17.setText("Nama Alat");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        btnTambahDataAlat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataAlat.png"))); // NOI18N
        btnTambahDataAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahDataAlatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahDataAlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahDataAlatMouseExited(evt);
            }
        });
        jPanel1.add(btnTambahDataAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("_______________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 260, 30));

        txtFieldHargaJual.setBorder(null);
        txtFieldHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHargaJualActionPerformed(evt);
            }
        });
        txtFieldHargaJual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldHargaJualKeyTyped(evt);
            }
        });
        jPanel1.add(txtFieldHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 190, 40));

        titleHargaJual.setText("Harga Jual");
        jPanel1.add(titleHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCariActionPerformed

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal-hover.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png")));
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan-hover.png")));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        btnBatal();
        
    }//GEN-LAST:event_btnBatalMouseClicked

    private void txtFieldKodeAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldKodeAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKodeAlatActionPerformed

    private void txtFieldBiayaProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldBiayaProduksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldBiayaProduksiActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        btnSimpanDataAlat();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tableAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlatMouseClicked
       int baris = tableAlat.getSelectedRow();
            txtFieldKodeAlat.setText(tableAlat.getValueAt(baris, 0).toString());
            txtFieldNamaAlat.setText(tableAlat.getValueAt(baris, 1).toString());
            txtFieldBiayaProduksi.setText(tableAlat.getValueAt(baris, 2).toString());
            txtFieldHargaJual.setText(tableAlat.getValueAt(baris, 3).toString());
            simpan = false;
    }//GEN-LAST:event_tableAlatMouseClicked

    private void txtFieldNamaAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaAlatActionPerformed

    private void txtFieldHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaJualActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png")));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnTambahDataAlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataAlatMouseEntered
        btnTambahDataAlat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataAlat.png")));
    }//GEN-LAST:event_btnTambahDataAlatMouseEntered

    private void btnTambahDataAlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataAlatMouseExited
        btnTambahDataAlat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataAlat-hover.png")));
    }//GEN-LAST:event_btnTambahDataAlatMouseExited

    private void txtFieldBiayaProduksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldBiayaProduksiKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
            titleBiayaProduksi.setForeground (Color.red);
        } else {
            titleBiayaProduksi.setForeground (Color.black);
        }
    }//GEN-LAST:event_txtFieldBiayaProduksiKeyTyped

    private void txtFieldHargaJualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldHargaJualKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)){
            evt.consume();
            titleHargaJual.setForeground (Color.red);
        } else {
            titleHargaJual.setForeground (Color.black);
        }
    }//GEN-LAST:event_txtFieldHargaJualKeyTyped

    private void btnTambahDataAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataAlatMouseClicked
        simpan = true;
        kodeAlatOtomatis();
        String nama = txtFieldNamaAlat.getText().trim();
        String biaya = txtFieldBiayaProduksi.getText().trim();
        String harga = txtFieldHargaJual.getText().trim();
        if (nama.isEmpty() || biaya.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Belum terisi semua", "TAMBAH DATA ERROR !", JOptionPane.ERROR_MESSAGE);
            try {
            } catch (Exception e) {

            }
            return;
        }
    }//GEN-LAST:event_btnTambahDataAlatMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        FMenuUtama21552011235 fm = new FMenuUtama21552011235();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void txtFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCariKeyReleased
        tampilDataAlat();
    }//GEN-LAST:event_txtFieldCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FAlat21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FAlat21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FAlat21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FAlat21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FAlat21552011235().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel btnTambahDataAlat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAlat;
    private javax.swing.JLabel titleBiayaProduksi;
    private javax.swing.JLabel titleHargaJual;
    private javax.swing.JTextField txtFieldBiayaProduksi;
    private javax.swing.JTextField txtFieldCari;
    private javax.swing.JTextField txtFieldHargaJual;
    private javax.swing.JTextField txtFieldKodeAlat;
    private javax.swing.JTextField txtFieldNamaAlat;
    // End of variables declaration//GEN-END:variables
}
