/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import koneksi.CKoneksi21552011235;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import session.UserSession;
import session.kodepeSession;
import session.namaSession;

/**
 *
 * @author albin
 */
public class FPenjualan21552011235 extends javax.swing.JFrame {
    Connection conn = CKoneksi21552011235.getKoneksi();
    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String sql, nama, email, level;
    Boolean simpan;
    private Object mapHargaJual;
    private Object request;
    String dbURL ="jdbc:mysql://localhost:3306/db_uts_pbo2_21552011235";
    String username = "root";
    String password = "";
    String ambil;

    
    public FPenjualan21552011235() {
        initComponents();
        dataComboBoxNamaAlat();
        tampilDataPenjualan();
        isikodePegawai();
        hakakses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    private void idunamaLogin() {
        txtFieldNamaPegawai.setText(namaSession.getnamaaLogin());
    }
    
    private void hakakses() {
        String user = UserSession.getUserLogin();

        if (user.equals("Produksi")) {
            dateTglPenjualan.setVisible(false);
            txtFieldKodePenjualan.setEnabled(false);
            txtFieldNamaPegawai.setEnabled(false);
            txtFieldHargaJual.setEnabled(false);
            txtFieldJumlah.setEnabled(false);
            btnTambahDataPenjualan.setEnabled(false);
            btnSimpan.setEnabled(false);
            System.out.println("");

        } else {
            System.out.println("");
        }
    }
    
    private void isikodePegawai() {
        try {
            sql = "select kodePegawai from tblpegawai";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String dd = rs.getString("kodePegawai");
            }
        } catch (Exception e) {
        }
    }
    
    
    public void tampilDataPenjualan() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Kode Jual");
        model.addColumn("Kode Alat");
        model.addColumn("Kode Pegawai");
        model.addColumn("Tanggal Jual");
        model.addColumn("Jumlah");

        try {
            int no = 1;
            if (txtFieldCari.getText().isEmpty()) {
                sql = "select * from tblpenjualan";
            } else {
                sql = "SELECT * FROM tblpenjualan WHERE kodeJual LIKE '%" + txtFieldCari.getText() + "%' OR kodeAlat LIKE '%" + txtFieldCari.getText() + "%'";

            }
            java.sql.Connection conn = (Connection) CKoneksi21552011235.getKoneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getInt(5)});

            }
           tablePenjualan.setModel(model);
        } catch (SQLException e) {
            System.out.println("error : " + e.getMessage());
        }
    }
    
private void dataComboBoxNamaAlat() {
    try {
        st = conn.createStatement();
        sql = "SELECT namaAlat, hargaJual FROM tblalat";
        rs = st.executeQuery(sql);

        // buat map untuk menampung nama alat dan harga jual
        Map<String, Integer> hargaMap = new HashMap<>();
        while (rs.next()) {
            String namaAlat = rs.getString("namaAlat");
            int hargaJual = rs.getInt("hargaJual");
            hargaMap.put(namaAlat, hargaJual);
        }

        // reset JComboBox namaAlat
        comboBoxNamaAlat.removeAllItems();

        // isi JComboBox namaAlat
        st = conn.createStatement();
        sql = "SELECT namaAlat FROM tblalat";
        rs = st.executeQuery(sql);
        while (rs.next()) {
            String namaAlat = rs.getString("namaAlat");
            comboBoxNamaAlat.addItem(namaAlat);
        }

        // tambahkan action listener pada JComboBox namaAlat
        comboBoxNamaAlat.addActionListener((ActionEvent e) -> {
            String namaAlat = (String) comboBoxNamaAlat.getSelectedItem();
            if (hargaMap.containsKey(namaAlat)) {
                int hargaJual = hargaMap.get(namaAlat);
                txtFieldHargaJual.setText(String.valueOf(hargaJual));
            } else {
                txtFieldHargaJual.setText("");
            }
        });

    } catch (SQLException ex) {
        ex.printStackTrace();
    }
}
    
    public String generateKodePenjualan(String namaAlat, Date tanggalPenjualan, int nomorUrut) {
        String[] words = namaAlat.split(" ");
        String kode = "";
        if (words.length == 1) {
            kode = words[0].substring(0, 3).toUpperCase();
        } else {
            for (String word : words) {
                kode += word.substring(0, 1).toUpperCase();
            }
        }
        DateFormat format = new SimpleDateFormat("ddMMyyyy");
        String tgl = format.format(tanggalPenjualan);

        try {
            Statement st = conn.createStatement();
            String sql = "SELECT MAX(kodeJual) AS kodeJual FROM tblpenjualan";
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                // Jika ada data kode penjualan di tabel penjualan
                String str_kd = rs.getString("kodeJual");
                if (str_kd == null) {
                    // Jika data tidak ada, eksekusi 4 digit terakhir dengan nilai 0001
                    String kodePenjualan = kode + tgl + String.format("%04d", 1);
                    return kodePenjualan;
                } else {
                    // Jika data ada, ekstrak nomor urut dan tambahkan 1
                    String kd = str_kd.substring(str_kd.length() - 4);
                    int int_code = Integer.parseInt(kd);
                    int_code++;
                    String a = String.format("%04d", int_code);
                    String kodePenjualan = kode + tgl + a;
                    return kodePenjualan;
                }
            } else {
                // Jika query tidak menghasilkan data
                throw new SQLException("Query MAX(kodeJual) AS kodeJual returned no data");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Jika terjadi kesalahan, lempar kembali exception
            throw new RuntimeException("Failed to generate kode penjualan", ex);
        }
    }
    
    public String getIdAlatByNama(String namaAlat) {
        String id = null;
        try (Connection conn = DriverManager.getConnection(dbURL, username, password);
                PreparedStatement stmt = conn.prepareStatement("SELECT kodeAlat FROM tblalat WHERE namaAlat = ?")) {
            stmt.setString(1, namaAlat);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    id = rs.getString("kodeAlat");
                }
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return id;
    }
    
    
    public String getKodePegawaiByNama(String kodePegawai) {
        String id = null;
        try (Connection conn = DriverManager.getConnection(dbURL, username, password);
                PreparedStatement stmt = conn.prepareStatement("SELECT kodePegawai FROM tblpegawai WHERE kodePegawai= ?")) {
            stmt.setString(1, kodePegawai);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    id = rs.getString("kodeAlat");
                }
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
        return id;
    }
    
    private void namaAlatDanHarga(){
        String namaAlat = comboBoxNamaAlat.getSelectedItem().toString();
        try {
            Connection conn = DriverManager.getConnection(dbURL, username, password);
            PreparedStatement stmt = conn.prepareStatement("SELECT hargaJual FROM tblalat WHERE namaAlat = ?");
            stmt.setString(1, namaAlat);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                txtFieldHargaJual.setText(rs.getString("hargaJual"));

            }
            conn.close();
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }

  
    private void btnSimpan(){
            try {
            String kodeJual = txtFieldKodePenjualan.getText();
            String namaAlat = comboBoxNamaAlat.getSelectedItem().toString();
            String kodeAlat = getIdAlatByNama(namaAlat);
            String kodePeg = kodepeSession.getkodepegLogin();
            //String namaPeg = txtFieldNamaPegawai.getText();
            String tglpenjualan = ((JTextField) dateTglPenjualan.getDateEditor().getUiComponent()).getText();
            DateFormat format = new SimpleDateFormat("MMMM d, yyyy", Locale.ENGLISH);
            Date date = format.parse(tglpenjualan);
            format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            String tglMasukJual = format.format(date);
            
            String jumlah = txtFieldJumlah.getText();

            if (kodeJual.isEmpty() || namaAlat.isEmpty() || kodePeg.isEmpty() || tglMasukJual.isEmpty() || jumlah.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Pastikan Data telah terisi semuanya. Ulangi kembali!", "DATA BELUM TERISI !", JOptionPane.WARNING_MESSAGE);
            } else {
                if (simpan == true) {
//                    sql = "INSERT INTO tblpenjualan (kodeJual, kodeAlat, kodePegawai, tglJual, jumlah) VALUES (?, (SELECT kodeAlat FROM tblalat WHERE namaDivisi = ?), (SELECT kodePegawai FROM tblpegawai WHERE nama = ?), ?, ?)";
                    sql = "INSERT INTO tblpenjualan VALUES (?, ?, ?, ?, ?)";
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, kodeJual);
                    ps.setString(2, kodeAlat);
                    ps.setString(3, kodePeg);
                    ps.setString(4, tglMasukJual);
                    ps.setString(5, jumlah);
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
                } else if (simpan == false) {
//                    sql = "UPDATE tblpenjualan SET jumlah=? WHERE kodeJual=?";
                    sql = "UPDATE tblpenjualan SET kodeJual=?, kodeAlat=?, kodePegawai=?, tglJual=?, jumlah=? WHERE kodeJual=?";
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, jumlah);
                    ps.setString(2, kodeJual);
                    JOptionPane.showMessageDialog(null, "Data berhasil diubah!");

                }
                ps.executeUpdate();
                tampilDataPenjualan ();

            }
        } catch (SQLException | ParseException e) {
            System.out.println("Error: " + e.getMessage());
     }
//                tampil();
//                new FPenjualan_21552011097().setVisible(true);
//                this.dispose();
//            }
//        } catch (SQLException | ParseException e) {
//            System.out.println("Error: " + e.getMessage());
//        }
  }
  private void btnBatal(){
        txtFieldKodePenjualan.setText(null);
        buttonGroup1.clearSelection();
        txtFieldHargaJual.setText(null);
        txtFieldJumlah.setText(null);
        dateTglPenjualan.setCalendar(null); 
        //txtFieldNamaPegawai.setText(null);
  }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldKodePenjualan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFieldHargaJual = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFieldNamaPegawai = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtFieldCari = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        comboBoxNamaAlat = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        dateTglPenjualan = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        txtFieldJumlah = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________________________________");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" 21552011235_Albi Mudakar Nasyabi");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Form Penjualan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, 30));

        txtFieldKodePenjualan.setBorder(null);
        txtFieldKodePenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldKodePenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldKodePenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 180, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("_______________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 260, 30));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png"))); // NOI18N
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalMouseExited(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, 50));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png"))); // NOI18N
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, 50));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("_______________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 240, 30));

        jLabel13.setText("Tanggal Penjualan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("_______________________________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 340, 30));

        txtFieldHargaJual.setBorder(null);
        txtFieldHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHargaJualActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 210, 40));

        jLabel15.setText("Harga Jual");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePenjualan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 740, 240));

        jLabel9.setText("Kode Penjualan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("______________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 280, 30));

        txtFieldNamaPegawai.setBorder(null);
        txtFieldNamaPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamaPegawaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldNamaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 230, 40));

        jLabel18.setText("Nama Pegawai");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("________________________________________");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 260, 30));

        txtFieldCari.setBorder(null);
        txtFieldCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldCariActionPerformed(evt);
            }
        });
        txtFieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtFieldCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 230, 30));

        jLabel20.setText("Masukan Kata Kunci");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 10));

        btnTambahDataPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataPenjualan.png"))); // NOI18N
        btnTambahDataPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahDataPenjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahDataPenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahDataPenjualanMouseExited(evt);
            }
        });
        jPanel1.add(btnTambahDataPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 230, 50));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("_______________________________");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 270, 30));

        comboBoxNamaAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNamaAlatActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxNamaAlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        jLabel23.setText("Nama Alat");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, 10));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 30, 30));
        jPanel1.add(dateTglPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("______________________________________");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 270, 30));

        txtFieldJumlah.setBorder(null);
        txtFieldJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 250, 40));

        jLabel17.setText("Jumlah");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldKodePenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldKodePenjualanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldKodePenjualanActionPerformed

    private void btnBatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseEntered
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal.png")));
    }//GEN-LAST:event_btnBatalMouseEntered

    private void btnBatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseExited
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnBatal-hover.png")));
    }//GEN-LAST:event_btnBatalMouseExited

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan.png")));
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnSimpan-hover.png")));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        btnBatal();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void txtFieldHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaJualActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        btnSimpan();
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void tablePenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePenjualanMouseClicked
        try {
            String name = namaSession.getnamaaLogin();
            int rowa = tablePenjualan.getSelectedRow();
            String kodePegawai2 = tablePenjualan.getValueAt(rowa, 2).toString();

            sql = "select nama from tblpegawai where kodePegawai='" + kodePegawai2 + "'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String dd = rs.getString("nama");
                if (!dd.equals(name)) {
                    JOptionPane.showMessageDialog(this, "Anda tidak dapat akses untuk mengubah data tersebut!", "AKSES DI TOLAK !", JOptionPane.ERROR_MESSAGE);
                    tablePenjualan.clearSelection();
                }
                try {
                    simpan = false;
                    int row = tablePenjualan.getSelectedRow();
                    String kodepenjualan = tablePenjualan.getValueAt(row, 0).toString();
                    String kodeAlat = tablePenjualan.getValueAt(row, 1).toString();
                    String kodePegawai = tablePenjualan.getValueAt(row, 2).toString();
                    String tglJual = tablePenjualan.getValueAt(row, 3).toString();
                    String jumlah = tablePenjualan.getValueAt(row, 4).toString();
                    txtFieldKodePenjualan.setText(kodepenjualan);
                    txtFieldJumlah.setText(jumlah);

                    try {
                        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tglJual);
                        dateTglPenjualan.setDate(date);
                    } catch (ParseException ex) {
                        System.out.println("Error: " + ex.getMessage());
                    }

                    try {
                        String sqlPegawai = "SELECT * FROM tblpegawai WHERE kodePegawai=?";
                        PreparedStatement psPegawai = conn.prepareStatement(sqlPegawai);
                        psPegawai.setString(1, kodePegawai);
                        ResultSet rsPegawai = psPegawai.executeQuery();
                        if (rsPegawai.next()) {
                            String namaPegawai = rsPegawai.getString("nama");
                            txtFieldNamaPegawai.setText(namaPegawai);
                        }
                    } catch (SQLException ex) {
                        System.out.println("Error: " + ex.getMessage());
                    }

                    if (!kodeAlat.isEmpty()) {
                        try {
                            String sqlAlat = "SELECT * FROM tblalat WHERE kodeAlat=?";
                            PreparedStatement psAlat = conn.prepareStatement(sqlAlat);
                            psAlat.setString(1, kodeAlat);
                            ResultSet rsAlat = psAlat.executeQuery();
                            if (rsAlat.next()) {
                                String namaAlat = rsAlat.getString("namaAlat");
                                for (int i = 0; i < comboBoxNamaAlat.getItemCount(); i++) {
                                    if (comboBoxNamaAlat.getItemAt(i).toString().equals(namaAlat)) {
                                        comboBoxNamaAlat.setSelectedIndex(i);
                                        break;
                                    }
                                }
                            }
                        } catch (SQLException ex) {
                            
                        }
                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tablePenjualanMouseClicked

    private void txtFieldNamaPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamaPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamaPegawaiActionPerformed

    private void txtFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldCariActionPerformed

    private void txtFieldCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCariKeyReleased
        tampilDataPenjualan();
    }//GEN-LAST:event_txtFieldCariKeyReleased

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
       btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24.png")));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
       btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-back-to-24-hover.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void txtFieldJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldJumlahActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        FMenuUtama21552011235 fm = new FMenuUtama21552011235();
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnTambahDataPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataPenjualanMouseClicked
        idunamaLogin();
        simpan = true;
        String namaAlat = comboBoxNamaAlat.getSelectedItem().toString();
        Date tanggalPenjualan = dateTglPenjualan.getDate();
        int nomorUrut = 1;
        String kodePenjualan = generateKodePenjualan(namaAlat, tanggalPenjualan, nomorUrut);
        txtFieldKodePenjualan.setText(kodePenjualan);

    }//GEN-LAST:event_btnTambahDataPenjualanMouseClicked

    private void btnTambahDataPenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataPenjualanMouseEntered
        btnTambahDataPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataPenjualan.png")));
    }//GEN-LAST:event_btnTambahDataPenjualanMouseEntered

    private void btnTambahDataPenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahDataPenjualanMouseExited
        btnTambahDataPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/btnTambahDataPenjualan-hover.png")));
    }//GEN-LAST:event_btnTambahDataPenjualanMouseExited

    private void comboBoxNamaAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNamaAlatActionPerformed
        namaAlatDanHarga();  
    }//GEN-LAST:event_comboBoxNamaAlatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPenjualan21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPenjualan21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPenjualan21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPenjualan21552011235.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPenjualan21552011235().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnBatal;
    public static final javax.swing.JLabel btnSimpan = new javax.swing.JLabel();
    public static final javax.swing.JLabel btnTambahDataPenjualan = new javax.swing.JLabel();
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxNamaAlat;
    private com.toedter.calendar.JDateChooser dateTglPenjualan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePenjualan;
    private javax.swing.JTextField txtFieldCari;
    private javax.swing.JTextField txtFieldHargaJual;
    private javax.swing.JTextField txtFieldJumlah;
    private javax.swing.JTextField txtFieldKodePenjualan;
    private javax.swing.JTextField txtFieldNamaPegawai;
    // End of variables declaration//GEN-END:variables

    /*    void setNamaPegawai(String nama) {
    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    Object btnTambahDataPenjualan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Object getBtnTambahData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
